name: "Screenshot terminal outputs"
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  screenshot-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: run-general
        run: |
          echo "Running general commands first!"
          chmod +x general.sh
          sudo ./general.sh

      - name: run-privileged
        run: |
          echo "Running privileged queries!"
          chmod +x privileged.sh
          sudo ./privileged.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: ./outputs
